import React,{useMemo}from'react';
import{Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const ym=d=>String(d||'').slice(0,7);
const monthLabel=k=>{if(!k)return'';const[y,m]=k.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')};
function monthKeys(n=6){const now=new Date();return Array.from({length:n},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-(n-1-i),1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`})}
function Card({ey,title,children}){return <article className="mn-card"><small>{ey}</small><h2>{title}</h2>{children}</article>}
export default function RadarExecutive({tx=[]}){
 const d=useMemo(()=>{const paid=tx.filter(x=>x.status==='paid');const months=monthKeys(6);const trend=months.map(k=>{const rows=paid.filter(x=>ym(x.occurred_on)===k);const revenue=rows.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0);const expense=rows.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0);return{month:monthLabel(k),revenue,expense,result:revenue-expense,coverage:expense?revenue/expense*100:(revenue?100:0)}});const current=trend[trend.length-1]||{};const prev=trend[trend.length-2]||{};const currentKey=months[months.length-1];const cats={};paid.filter(x=>ym(x.occurred_on)===currentKey&&x.kind==='expense').forEach(x=>cats[x.category||'Outros']=(cats[x.category||'Outros']||0)+Number(x.amount||0));const categories=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([category,value])=>({category,value}));const coverage=current.expense?current.revenue/current.expense*100:(current.revenue?100:0);const compensation=current.revenue-current.expense;const expenseRatio=current.revenue?current.expense/current.revenue*100:0;const revDelta=prev.revenue?((current.revenue-prev.revenue)/prev.revenue*100):0;const expDelta=prev.expense?((current.expense-prev.expense)/prev.expense*100):0;return{trend,categories,coverage,compensation,expenseRatio,revDelta,expDelta}},[tx]);
 return <><div className="mn-grid2"style={{marginTop:18}}><Card ey="COMPARATIVO · 6 MESES" title="Receitas, despesas e resultado"><div className="mn-chart"><ResponsiveContainer><LineChart data={d.trend}><CartesianGrid vertical={false}strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis tickFormatter={x=>`${Math.round(x/1000)}k`}/><Tooltip formatter={x=>money(x)}/><Line type="monotone"dataKey="revenue"name="Receitas"stroke="#18c878"strokeWidth={3}/><Line type="monotone"dataKey="expense"name="Despesas"stroke="#6d8177"strokeWidth={3}/><Line type="monotone"dataKey="result"name="Resultado"stroke="#1f6feb"strokeWidth={2}/></LineChart></ResponsiveContainer></div></Card><Card ey="COBERTURA E COMPENSAÇÃO" title="Quanto a receita cobre as despesas"><div className="mn-score"><strong>{d.coverage.toFixed(1)}%</strong></div><p>{d.coverage>=100?`As receitas cobrem as despesas e geram ${money(d.compensation)} de excedente.`:`As receitas ainda não cobrem as despesas. Gap de ${money(Math.abs(d.compensation))}.`}</p><div className="mn-score-breakdown"><div><span>Despesa / receita</span><b>{d.expenseRatio.toFixed(1)}%</b><i><em style={{width:Math.min(100,d.expenseRatio)+'%'}}/></i></div><div><span>Receita vs mês anterior</span><b>{d.revDelta>=0?'+':''}{d.revDelta.toFixed(1)}%</b><i><em style={{width:Math.min(100,Math.abs(d.revDelta))+'%'}}/></i></div><div><span>Despesa vs mês anterior</span><b>{d.expDelta>=0?'+':''}{d.expDelta.toFixed(1)}%</b><i><em style={{width:Math.min(100,Math.abs(d.expDelta))+'%'}}/></i></div></div></Card></div><div className="mn-grid2"style={{marginTop:18}}><Card ey="ESTRUTURA DE CUSTOS" title="Despesas por categoria · mês atual"><div className="mn-chart"><ResponsiveContainer><BarChart data={d.categories}layout="vertical"margin={{left:15}}><CartesianGrid horizontal={false}strokeDasharray="3 3"/><XAxis type="number"tickFormatter={x=>`${Math.round(x/1000)}k`}/><YAxis type="category"dataKey="category"width={95}/><Tooltip formatter={x=>money(x)}/><Bar dataKey="value"name="Despesas"fill="#6d8177"radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div>{!d.categories.length&&<p>Sem despesas pagas no mês para comparar.</p>}</Card><Card ey="PONTO DE EQUILÍBRIO" title="Receita necessária x realizada"><div className="mn-chart"><ResponsiveContainer><BarChart data={[{name:'Mês atual',necessaria:d.trend.at(-1)?.expense||0,realizada:d.trend.at(-1)?.revenue||0}]}><CartesianGrid vertical={false}strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis tickFormatter={x=>`${Math.round(x/1000)}k`}/><Tooltip formatter={x=>money(x)}/><Bar dataKey="necessaria"name="Receita para cobrir despesas"fill="#6d8177"/><Bar dataKey="realizada"name="Receita realizada"fill="#18c878"/></BarChart></ResponsiveContainer></div><p>{d.compensation>=0?'Operação acima do ponto de equilíbrio financeiro do período.':'Operação abaixo do ponto de equilíbrio financeiro do período.'}</p></Card></div></>
}
