import React,{useMemo,useState}from'react';
import{Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const iso=d=>d.toISOString().slice(0,10);
const parse=d=>new Date(String(d||'').slice(0,10)+'T12:00:00');
const startMonth=d=>new Date(d.getFullYear(),d.getMonth(),1);
const endMonth=d=>new Date(d.getFullYear(),d.getMonth()+1,0);
const monthValue=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const monthLabel=k=>{const[y,m]=k.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}).replace('.','')};
function Card({ey,title,children}){return <article className="mn-card"><small>{ey}</small><h2>{title}</h2>{children}</article>}
function Kpi({t,v,s,good}){return <article className="mn-kpi"><div><span>{t}</span></div><strong>{v}</strong>{s&&<small className={good?'pos':''}>{s}</small>}</article>}
function rangeFor(mode,selectedMonth){const now=new Date();let start,end=now,label='Mês corrente';if(mode==='current'){start=startMonth(now);label='Mês corrente'}else if(mode==='previous'){const p=new Date(now.getFullYear(),now.getMonth()-1,1);start=startMonth(p);end=endMonth(p);label='Último mês'}else if(mode==='60'){start=new Date(now);start.setDate(start.getDate()-59);label='Últimos 60 dias'}else if(mode==='90'){start=new Date(now);start.setDate(start.getDate()-89);label='Últimos 90 dias'}else if(mode==='12m'){start=new Date(now.getFullYear(),now.getMonth()-11,1);label='Últimos 12 meses'}else{const[y,m]=selectedMonth.split('-').map(Number);const d=new Date(y,m-1,1);start=startMonth(d);end=endMonth(d);label=new Date(y,m-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}return{start,end,label}}
function weekKey(d){const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return iso(x)}
function bucketKey(date,granularity){const d=parse(date);if(granularity==='day')return iso(d);if(granularity==='week')return weekKey(d);return monthValue(d)}
function bucketLabel(key,granularity){if(granularity==='day')return new Date(key+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});if(granularity==='week'){const d=new Date(key+'T12:00:00');return`Sem ${d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}`}return monthLabel(key)}
export default function RadarExecutive({tx=[],balance=0}){
 const[mode,setMode]=useState('current');const[granularity,setGranularity]=useState('day');const[selectedMonth,setSelectedMonth]=useState(monthValue(new Date()));const[source,setSource]=useState('statements');const[tab,setTab]=useState('summary');
 const d=useMemo(()=>{const{start,end,label}=rangeFor(mode,selectedMonth);let paid=tx.filter(x=>x.status==='paid'&&!x.is_import_duplicate);if(source==='statements')paid=paid.filter(x=>!!x.source_name);paid=paid.filter(x=>{const dt=parse(x.occurred_on);return dt>=start&&dt<=end});const buckets={};paid.forEach(x=>{const k=bucketKey(x.occurred_on,granularity);if(!buckets[k])buckets[k]={revenue:0,expense:0};if(x.kind==='income')buckets[k].revenue+=Number(x.amount||0);if(x.kind==='expense')buckets[k].expense+=Number(x.amount||0)});const trend=Object.keys(buckets).sort().map(k=>({period:bucketLabel(k,granularity),revenue:buckets[k].revenue,expense:buckets[k].expense,result:buckets[k].revenue-buckets[k].expense}));const revenue=paid.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0);const expense=paid.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0);const cats={};paid.filter(x=>x.kind==='expense').forEach(x=>cats[x.category||'Outros']=(cats[x.category||'Outros']||0)+Number(x.amount||0));const categories=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([category,value])=>({category,value}));const coverage=expense?revenue/expense*100:(revenue?100:0);const compensation=revenue-expense;const expenseRatio=revenue?expense/revenue*100:0;const margin=revenue?compensation/revenue*100:0;return{trend,categories,coverage,compensation,expenseRatio,revenue,expense,label,margin,count:paid.length}},[tx,mode,granularity,selectedMonth,source]);
 const status=d.compensation>=0?'Superávit no período':'Déficit no período';
 return <><article className="mn-card"style={{marginTop:18}}><small>ANÁLISE CONSOLIDADA</small><h2>Visão financeira por período</h2><div className="mx-filterbar"><label className="mc-field"><span>Base</span><select value={source}onChange={e=>setSource(e.target.value)}><option value="statements">Extratos bancários</option><option value="all">Todos os lançamentos pagos</option></select></label><label className="mc-field"><span>Período</span><select value={mode}onChange={e=>setMode(e.target.value)}><option value="current">Mês corrente</option><option value="previous">Último mês</option><option value="60">Últimos 60 dias</option><option value="90">Últimos 90 dias</option><option value="12m">Últimos 12 meses</option><option value="custom">Selecionar mês</option></select></label>{mode==='custom'?<label className="mc-field"><span>Mês</span><input type="month"max={monthValue(new Date())}value={selectedMonth}onChange={e=>setSelectedMonth(e.target.value)}/></label>:<label className="mc-field"><span>Agrupar por</span><select value={granularity}onChange={e=>setGranularity(e.target.value)}><option value="day">Dias</option><option value="week">Semanas</option><option value="month">Meses</option></select></label>}<div><b>{d.label}</b><span className="mx-data-tag">{d.count} movimentações</span></div></div>{mode==='custom'&&<div style={{marginTop:10,maxWidth:260}}><label className="mc-field"><span>Agrupar por</span><select value={granularity}onChange={e=>setGranularity(e.target.value)}><option value="day">Dias</option><option value="week">Semanas</option><option value="month">Meses</option></select></label></div>}<div className="mx-tabs">{[['summary','Resumo'],['flow','Fluxo'],['costs','Despesas'],['health','Diagnóstico']].map(([id,label])=><button key={id}className={tab===id?'active':''}onClick={()=>setTab(id)}>{label}</button>)}</div></article>
 <div className="mn-kpis"style={{marginTop:18}}><Kpi t="Saldo disponível"v={money(balance)}s="Saldo das contas selecionadas"/><Kpi t={`Entradas · ${d.label}`}v={money(d.revenue)}good/><Kpi t={`Saídas · ${d.label}`}v={money(d.expense)}/><Kpi t={`Resultado · ${d.label}`}v={money(d.compensation)}s={d.revenue?`Margem ${d.margin.toFixed(1)}%`:'Sem receita no período'}good={d.compensation>=0}/></div>
 {tab==='summary'&&<><div className="mn-grid2"style={{marginTop:18}}><Card ey="RESUMO EXECUTIVO"title="Leitura rápida do período"><div className="mx-summary-line"><div><span>Cobertura das despesas</span><b>{d.coverage.toFixed(1)}%</b></div><div><span>Despesa sobre receita</span><b>{d.expenseRatio.toFixed(1)}%</b></div><div><span>Situação</span><b className={d.compensation>=0?'pos':'neg'}>{status}</b></div></div><p className="mx-section-note"style={{marginTop:14}}>{d.coverage>=100?`As receitas cobrem integralmente as despesas e deixam ${money(d.compensation)} de excedente.`:`Faltam ${money(Math.abs(d.compensation))} para que as receitas cubram as despesas do período.`}</p></Card><Card ey="PONTO DE EQUILÍBRIO"title="Receita necessária x realizada"><div className="mn-chart small"><ResponsiveContainer><BarChart data={[{name:d.label,necessaria:d.expense,realizada:d.revenue}]}><CartesianGrid vertical={false}strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis tickFormatter={x=>`${Math.round(x/1000)}k`}/><Tooltip formatter={x=>money(x)}/><Bar dataKey="necessaria"name="Receita necessária"fill="#6d8177"/><Bar dataKey="realizada"name="Receita realizada"fill="#18c878"/></BarChart></ResponsiveContainer></div></Card></div></>}
 {tab==='flow'&&<Card ey="EVOLUÇÃO DO PERÍODO"title="Receitas, despesas e resultado"><div className="mn-chart"><ResponsiveContainer><LineChart data={d.trend}><CartesianGrid vertical={false}strokeDasharray="3 3"/><XAxis dataKey="period"/><YAxis tickFormatter={x=>`${Math.round(x/1000)}k`}/><Tooltip formatter={x=>money(x)}/><Line type="monotone"dataKey="revenue"name="Receitas"stroke="#18c878"strokeWidth={3}/><Line type="monotone"dataKey="expense"name="Despesas"stroke="#6d8177"strokeWidth={3}/><Line type="monotone"dataKey="result"name="Resultado"stroke="#1f6feb"strokeWidth={2}/></LineChart></ResponsiveContainer></div>{!d.trend.length&&<div className="mx-empty">Sem movimentações para o período selecionado.</div>}</Card>}
 {tab==='costs'&&<Card ey="ESTRUTURA DE DESPESAS"title={`Despesas por categoria · ${d.label}`}><div className="mn-chart"><ResponsiveContainer><BarChart data={d.categories}layout="vertical"margin={{left:15}}><CartesianGrid horizontal={false}strokeDasharray="3 3"/><XAxis type="number"tickFormatter={x=>`${Math.round(x/1000)}k`}/><YAxis type="category"dataKey="category"width={95}/><Tooltip formatter={x=>money(x)}/><Bar dataKey="value"name="Despesas"fill="#6d8177"radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div>{!d.categories.length&&<div className="mx-empty">Sem despesas pagas no período selecionado.</div>}</Card>}
 {tab==='health'&&<div className="mn-grid2"><Card ey="COBERTURA E COMPENSAÇÃO"title="Capacidade de cobertura"><div className="mn-score"><strong>{d.coverage.toFixed(1)}%</strong></div><div className="mn-score-breakdown"><div><span>Receitas</span><b>{money(d.revenue)}</b></div><div><span>Despesas</span><b>{money(d.expense)}</b></div><div><span>Despesa / receita</span><b>{d.expenseRatio.toFixed(1)}%</b><i><em style={{width:Math.min(100,d.expenseRatio)+'%'}}/></i></div></div></Card><Card ey="INTERPRETAÇÃO"title="O que os números indicam"><p className="mx-section-note">{d.compensation>=0?'O período apresenta resultado positivo. O foco deve ser preservar margem, controlar crescimento das despesas e direcionar o excedente.':'O período apresenta resultado negativo. Priorize despesas relevantes, compromissos vencidos e fontes de receita de maior recorrência.'}</p><div className="mx-summary-line"><div><span>Resultado</span><b className={d.compensation>=0?'pos':'neg'}>{money(d.compensation)}</b></div><div><span>Margem</span><b>{d.margin.toFixed(1)}%</b></div><div><span>Base</span><b>{source==='statements'?'Extratos':'Lançamentos pagos'}</b></div></div></Card></div>}
 </>
}
